{% set version = "0.9.2" %}
{% set sha256 = "56f1f288778ceb738f1974ec95de10493936f059a93b7f8717f88c1c6d01b67a" %}

package:
  name: hck
  version: {{ version }}

source:
  url: https://github.com/sstadick/hck/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - pkg-config
    - make
    - cmake
    - cargo-bundle-licenses

test:
  commands:
    - hck --help

about:
  home: https://github.com/sstadick/hck
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Header aware, faster replacement for cut.

extra:
  recipe-maintainers:
    - sstadick
