{% set version = "0.7.3" %}
{% set sha256 = "3c0c9c85dfebd047d49c23a5722f9aabde5e560faabadc088b680baf6701a067" %}

package:
  name: hck
  version: {{ version }}

source:
  url: https://github.com/sstadick/hck/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - pkg-config
    - make
    - cmake
    - cargo-bundle-licenses

test:
  commands:
    - hck --help

about:
  home: https://github.com/sstadick/hck
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Header aware, faster replacement for cut.

extra:
  recipe-maintainers:
    - sstadick
