schema_version: 1

context:
  version: "0.11.5"

package:
  name: hck
  version: ${{ version }}

source:
  url: https://github.com/sstadick/hck/archive/v${{ version }}.tar.gz
  sha256: 5ce5fc816e9e009dafe8c42a0bd6b9e6c8b7ca5a839af6a797fba9accc569242

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - make
    - cmake
    - cargo-bundle-licenses

tests:
  - script:
      - hck --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Header aware, faster replacement for cut.
  homepage: https://github.com/sstadick/hck

extra:
  recipe-maintainers:
    - danielnachun
    - sstadick
