schema_version: 1

context:
  version: "0.11.6"

package:
  name: hck
  version: ${{ version }}

source:
  url: https://github.com/sstadick/hck/archive/v${{ version }}.tar.gz
  sha256: b9821c4de35308d8d1d9e979da39f8a7effd82d2e0b1f4f7b1c83bc48ab8da20

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - make
    - cmake
    - cargo-bundle-licenses

tests:
  - script:
      - hck --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Header aware, faster replacement for cut.
  homepage: https://github.com/sstadick/hck

extra:
  recipe-maintainers:
    - danielnachun
    - sstadick
